server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgres://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-failure: payment-failure
    consumer:
      group-id: payment-group
      auto-offset-reset: latest
logging:
  level:
    org:
      apache:
        kafka: off