server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgres://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:products}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect